### ISSUE TITLE
Type error in `src/declare_translation`

### ISSUE THREAD

**Issue by ichistmeinname** [mlasson/paramcoq#1]
I have OCaml version 4.02.2 installed as well as camlp4, am running on Mac OS 10.10. and get the following exception when I try to install your extension via `make`:

    Error: This function has type
              Term.constr ->
              Globnames.Refset.t * Globnames.Refset.t Globnames.Refmap.t
              It is applied to too many arguments; maybe you forgot a `;'.
    make[1]: *** [src/declare_translation.cmo] Error 2

Are there any dependencies that I do not fulfil or is there another reason for this error?

**Comment by mlasson** [comment]
Hello ! 
I need to update the code (which is 3 month old) to make it compile with the current coq trunk. 
I'll try to do this as soon as possible (I'll try to do this this weekend); in the mean time, you use an old version of coq trunk like by cloning my fork: https://github.com/mlasson/coq).

**Comment by ichistmeinname** [comment]
Now I'm confused, because I did checkout the repo you mention in the README. Isn't that repo the right version?

**Comment by mlasson** [comment]
Hi ! 

It was my fault.
You can "git pull" inside paramcoq directory to apply a fix and "make" to recompile (no need to recompile coq). 

I am waiting for coq 8.5 to get officially out in order to have a "real coq" version to be compatible with (so in a not so distant future, you won't need to recompile coq at all to use the plugin). If you have any problem to use the plugin, please do not hesitate to contact me.

**Comment by ichistmeinname** [comment]
Thanks, now it works!
